### ISSUE TITLE
Crashing Slim Recents on App Sidebar config (still problem at 2019.04.26)

### ISSUE THREAD

**Issue by klorinczi** [ResurrectionRemix/frameworks_opt_slimrecent#1]
Crashing Slim Recents on App Sidebar config. 

Bug report
App side bar content menu will not open 

Device name:
hlte (Galaxy Note 3 N9005)

ROM Ver: 
RR-N-v5.8.5-20180313-hlte-Official-vidwhal.zip

Detailed Description:
The  App Sidebar content menu will not open and it  crashes the settings app. 
(Setting>Configuration>Recent>Slim recents settings>App side bar content)

The following bug report seems to be similar:
https://plus.google.com/105784414123029664046/posts/aEyb6g36CRC

Logcat:
W/WindowManager(  825): Attempted to remove non-existing token: android.os.Binder@7988f25
W/TileUtils( 5055): Found com.android.settings.Settings$PaymentSettingsActivity for intent Intent { act=com.android.settings.action.SETTINGS pkg=com.android.settings } missing metadata com.android.settings.category
W/TileUtils( 5055): Found org.cyanogenmod.cmparts.input.ButtonSettings for intent Intent { act=com.android.settings.action.EXTRA_SETTINGS } missing metadata com.android.settings.category
W/TileUtils( 5055): Found org.cyanogenmod.cmparts.statusbar.StatusBarSettings for intent Intent { act=com.android.settings.action.EXTRA_SETTINGS } missing metadata com.android.settings.category
W/TileUtils( 5055): Found com.android.systemui.tuner.TunerActivity for intent Intent { act=com.android.settings.action.EXTRA_SETTINGS } missing metadata 
W/ActivityManager(  825):   Force finishing activity com.android.settings/.rr.SlimRecentAppSidebarActivity
W/DropBoxManagerService(  825): Dropping: system_app_crash (1968 > 0 bytes)
W/ActivityManager(  825):   Force finishing activity com.android.settings/.SubSettings
W/ContextImpl(  825): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:877 com.android.server.am.AppErrors.crashApplicationInner:375 com.android.server.am.AppErrors.crashApplication:309 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:13754 com.android.server.am.ActivityManagerService.handleApplicationCrash:13736 
W/BroadcastQueue(  825): Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to ProcessRecord{13fa7d 27506:org.rojekti.clipper/u0a104} (pid=27506, uid=10104) requires android.permission.READ_LOGS due to sender android (uid 1000)
W/BroadcastQueue(  825): Permission Denial: receiving Intent { act=android.bluetooth.a2dp.profile.action.PLAYING_STATE_CHANGED flg=0x4000010 (has extras) } to ProcessRecord{13fa7d 27506:org.rojekti.clipper/u0a104} (pid=27506, uid=10104) requires android.permission.BLUETOOTH due to sender com.android.bluetooth (uid 1002)
W/ActivityManager(  825): Activity pause timeout for ActivityRecord{750894e u0 com.android.settings/.rr.SlimRecentAppSidebarActivity t95 f}
W/System  ( 5737): ClassLoader referenced unknown path: /system/priv-app/Settings/lib/arm
W/AppOps  (  825): Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
W/DropBoxManagerService(  825): Dropping: system_server_wtf (2347 > 0 bytes)
W/BroadcastQueue(  825): Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to ProcessRecord{13fa7d 27506:org.rojekti.clipper/u0a104} (pid=27506, uid=10104) requires android.permission.READ_LOGS due to sender android (uid 1000)
W/TileUtils( 5737): Found com.android.settings.Settings$PaymentSettingsActivity for intent Intent { act=com.android.settings.action.SETTINGS pkg=com.android.settings } missing metadata com.android.settings.category
W/TileUtils( 5737): Found org.cyanogenmod.cmparts.input.ButtonSettings for intent Intent { act=com.android.settings.action.EXTRA_SETTINGS } missing metadata com.android.settings.category
W/TileUtils( 5737): Found org.cyanogenmod.cmparts.statusbar.StatusBarSettings for intent Intent { act=com.android.settings.action.EXTRA_SETTINGS } missing metadata com.android.settings.category
W/TileUtils( 5737): Found com.android.systemui.tuner.TunerActivity for intent Intent { act=com.android.settings.action.EXTRA_SETTINGS } missing metadata 
W/TileUtils( 5737): Found com.android.settings.Settings$PaymentSettingsActivity for intent Intent { act=com.android.settings.action.SETTINGS pkg=com.android.settings } missing metadata com.android.settings.category
W/TileUtils( 5737): Found org.cyanogenmod.cmparts.input.ButtonSettings for intent Intent { act=com.android.settings.action.EXTRA_SETTINGS } missing metadata com.android.settings.category
W/TileUtils( 5737): Found org.cyanogenmod.cmparts.statusbar.StatusBarSettings for intent Intent { act=com.android.settings.action.EXTRA_SETTINGS } missing metadata com.android.settings.category
W/TileUtils( 5737): Found com.android.systemui.tuner.TunerActivity for intent Intent { act=com.android.settings.action.EXTRA_SETTINGS } missing metadata 
W/auditd  (  308): type=1307 audit(0.0:8286): cwd="/"
W/auditd  (  308): type=1302 audit(0.0:8286): item=0 name="/sys/class/power_supply/battery/batt_read_raw_soc" inode=29417 dev=00:0f mode=0100666 ouid=0 ogid=0 rdev=00:00 obj=u:object_r:sysfs:s0
W/auditd  (  308): type=1327 audit(0.0:8286): proctitle="ccc71.bmw.pro"
W/auditd  (  308): type=1320 audit(0.0:8286): 
W/auditd  (  308): type=1307 audit(0.0:8287): cwd="/"
W/auditd  (  308): type=1302 audit(0.0:8287): item=0 name="/sys/class/power_supply/battery/batt_read_raw_soc" inode=29417 dev=00:0f mode=0100666 ouid=0 ogid=0 rdev=00:00 obj=u:object_r:sysfs:s0
W/auditd  (  308): type=1327 audit(0.0:8287): proctitle="ccc71.bmw.pro"
W/auditd  (  308): type=1320 audit(0.0:8287): 
W/WindowManager(  825): Attempted to remove non-existing token: android.os.Binder@193c207
W/BroadcastQueue(  825): Permission Denial: receiving Intent { act=android.bluetooth.a2dp.profile.action.PLAYING_STATE_CHANGED flg=0x4000010 (has extras) } to ProcessRecord{13fa7d 27506:org.rojekti.clipper/u0a104} (pid=27506, uid=10104) requires android.permission.BLUETOOTH due to sender com.android.bluetooth (uid 1002)
W/WindowManager(  825): Attempted to remove non-existing token: android.os.Binder@4cb3659
W/BroadcastQueue(  825): Permission Denial: receiving Intent { act=android.bluetooth.a2dp.profile.action.PLAYING_STATE_CHANGED flg=0x4000010 (has extras) } to ProcessRecord{13fa7d 27506:org.rojekti.clipper/u0a104} (pid=27506, uid=10104) requires android.permission.BLUETOOTH due to sender com.android.bluetooth (uid 1002)

**Comment by fgl27** [comment]
too old closing.

**Comment by klorinczi** [comment]
The crash still happens in RR N v5.8.5 release. 
I still ask to fix it.
